apiVersion: 1
datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: "sensiot_org"
      defaultBucket: "sensiot"
      tlsSkipVerify: true
      httpMode: POST
    secureJsonData:
      token: $SENSIOT_INFLUX_TOKEN
