global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'chirpstack_core'
    static_configs:
      - targets: ['chirpstack-docker_chirpstack_1:9108']

  - job_name: 'chirpstack_gateway_bridge_eu868'
    static_configs:
      - targets: ['chirpstack-docker_chirpstack-gateway-bridge-eu868_1:9109']

  - job_name: 'chirpstack_gateway_bridge_us915'
    static_configs:
      - targets: ['chirpstack-docker_chirpstack-gateway-bridge-us915_1:9113']

  - job_name: 'chirpstack_gateway_bridge_kr920'
    static_configs:
      - targets: ['chirpstack-docker_chirpstack-gateway-bridge-kr920_1:9111']

  - job_name: 'chirpstack_gateway_bridge_in865'
    static_configs:
      - targets: ['chirpstack-docker_chirpstack-gateway-bridge-in865_1:9110']

  - job_name: 'chirpstack_gateway_bridge_ru864'
    static_configs:
      - targets: ['chirpstack-docker_chirpstack-gateway-bridge-ru864_1:9112']
