version: "3.8"

services:
  mqtt:
    image: eclipse-mosquitto
    ports:
      - "1888:1883"  # Expose local MQTT on port 1888 mapped to container port 1883
    volumes:
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - fog-sensiot_network
    restart: always

  fog_manager:
    build: ./fog-manager
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      # Global broker is now the one used by the updated ChirpStack (EMQX via HAProxy)
      - MQTT_BROKER_GLOBAL=haproxy
      # Local broker used for communication between fog manager and fog nodes
      - MQTT_BROKER_LOCAL=mqtt
      - MQTT_PORT=1883
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config:/app/config
    user: "1000:984"
    depends_on:
      - mqtt
    networks:
      - fog-sensiot_network
      - chirpstack-docker_lorawan
    dns:
      - 8.8.8.8
      - 8.8.4.4
    restart: unless-stopped

networks:
  fog-sensiot_network:
    external: true
  chirpstack-docker_lorawan:
    external: true
