version: '3.7'

networks:
  chirpstack-docker_lorawan:
    external: true
  fog-nodes_fog_network:
    external: true

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_monitor
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9091:9090"
    networks:
      - chirpstack-docker_lorawan
      - fog-nodes_fog_network
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8082:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
    networks:
      - chirpstack-docker_lorawan
      - fog-nodes_fog_network
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    ports:
      - "9100:9100"
    networks:
      - chirpstack-docker_lorawan
      - fog-nodes_fog_network
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3005:3000"
    volumes:
      - ./grafana-provisioning/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana-provisioning/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana-provisioning/provisioning/config:/etc/grafana/provisioning/config
      - ./grafana-provisioning/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - chirpstack-docker_lorawan
      - fog-nodes_fog_network