# See https://www.chirpstack.io/gateway-bridge/install/config/ for a full
# configuration example and documentation.

[integration.mqtt.auth.generic]
servers=["ssl://chirpstack-haproxy:8883"]
ca_cert="/etc/chirpstack-gateway-bridge/mqtt-certs/ca.crt"
tls_cert="/etc/chirpstack-gateway-bridge/mqtt-certs/client.crt"
tls_key="/etc/chirpstack-gateway-bridge/mqtt-certs/client.key"
username=""
password=""
