version: '3.7'

volumes:
  emqx1_data:
  emqx2_data:
  emqx3_data:

services:
  #############################################################################
  #                             Region US915                                  #
  #############################################################################
  fog-node-us915:
    build: .
    restart: always
    env_file:
      - ./config/config-us915.env
    networks:
      - fog_network
      - chirpstack-docker_lorawan

  #############################################################################
  #                             Region EU868                                  #
  #############################################################################
  fog-node-eu868:
    build: .
    restart: always
    env_file:
      - ./config/config-eu868.env
    networks:
      - fog_network
      - chirpstack-docker_lorawan

  #############################################################################
  #                             Region RU864                                  #
  #############################################################################
  fog-node-ru864:
    build: .
    restart: always
    env_file:
      - ./config/config-ru864.env
    networks:
      - fog_network
      - chirpstack-docker_lorawan

  #############################################################################
  #                             Region IN865                                  #
  #############################################################################
  fog-node-in865:
    build: .
    restart: always
    env_file:
      - ./config/config-in865.env
    networks:
      - fog_network
      - chirpstack-docker_lorawan

  #############################################################################
  #                           Load Balancer (HAProxy)                         #
  #############################################################################
  haproxy:
      image: haproxy:2.6
      restart: always
      networks:
        - fog_network
        - chirpstack-docker_lorawan
      volumes:
        - ./config/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      ports:
        - "2883:1883"  # Expose central broker on host port 2883
      healthcheck:
        test: [ "CMD", "nc", "-z", "localhost", "1883" ]
        interval: 10s
        timeout: 5s
        retries: 3

    #############################################################################
    #                           EMQX MQTT CLUSTER (3 Nodes)                     #
    #############################################################################
  emqx1:
    image: emqx:5.0
    container_name: emqx_node1
    restart: always
    environment:
        - "EMQX_NAME=emqx"
        - "EMQX_HOST=node1.emqx.io"
        - "EMQX_NODE__COOKIE=mystrongsecretcookie123"
        - "EMQX_CLUSTER__DISCOVERY_STRATEGY=static"
        - "EMQX_CLUSTER__STATIC__SEEDS=emqx@node1.emqx.io,emqx@node2.emqx.io,emqx@node3.emqx.io"
    volumes:
      - emqx1_data:/opt/emqx/data
    networks:
      fog_network:
        aliases:
          - node1.emqx.io
    healthcheck:
        test: [ "CMD", "/opt/emqx/bin/emqx_ctl", "status" ]
        interval: 5s
        timeout: 25s
        retries: 5
    ports:
      - "18084:18083"  # Dashboard mapping
    deploy:
      resources:
        limits:
          memory: 2G

  emqx2:
    image: emqx:5.0
    container_name: emqx_node2
    restart: always
    networks:
      fog_network:
        aliases:
          - node2.emqx.io
    volumes:
      - emqx2_data:/opt/emqx/data
    environment:
      - "EMQX_NAME=emqx"
      - "EMQX_HOST=node2.emqx.io"
      - "EMQX_NODE__COOKIE=mystrongsecretcookie123"
      - "EMQX_CLUSTER__DISCOVERY_STRATEGY=static"
      - "EMQX_CLUSTER__STATIC__SEEDS=emqx@node1.emqx.io,emqx@node2.emqx.io,emqx@node3.emqx.io"
    healthcheck:
        test: [ "CMD", "/opt/emqx/bin/emqx_ctl", "status" ]
        interval: 5s
        timeout: 25s
        retries: 5
    deploy:
      resources:
        limits:
          memory: 2G

  emqx3:
    image: emqx:5.0
    container_name: emqx_node3
    restart: always
    networks:
      fog_network:
        aliases:
          - node3.emqx.io
    volumes:
      - emqx3_data:/opt/emqx/data
    environment:
      - "EMQX_NAME=emqx"
      - "EMQX_HOST=node3.emqx.io"
      - "EMQX_NODE__COOKIE=mystrongsecretcookie123"
      - "EMQX_CLUSTER__DISCOVERY_STRATEGY=static"
      - "EMQX_CLUSTER__STATIC__SEEDS=emqx@node1.emqx.io,emqx@node2.emqx.io,emqx@node3.emqx.io"
    healthcheck:
        test: [ "CMD", "/opt/emqx/bin/emqx_ctl", "status" ]
        interval: 5s
        timeout: 25s
        retries: 5
    deploy:
      resources:
        limits:
          memory: 2G

networks:
  fog_network:
    driver: bridge
  chirpstack-docker_lorawan:
    external: true
